apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: praksa-task-brojac-pvc-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
