apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}-deployment-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name}}-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}-{{ .Values.env }}
    spec:
      containers:
        - name: {{ .Values.name}}-{{ .Values.env }}
          image: "{{ .Values.image.repository }}:{{ .Values.env }}-{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
