replicaCount: 2

env: qa

image:
  repository: ghcr.io/gusmarko/praksa-task-api/praksa-task-api
  tag: latest
  pullPolicy: Always

name: praksa-task-api

service:
  type: ClusterIP
  port: 8001

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

persistence:
  size: 1Gi
  accessMode: ReadWriteOnce
  mountPath: /data


