replicaCount: 5

env: uat

name: praksa-task-api

image:
  repository: ghcr.io/gusmarko/praksa-task-api/praksa-task-api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8002

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  mountPath: /data

namespace: praksa-task-uat


