namespace: test-dev
appName: test
ingress:
  enabled: true
  className: nginx

  rules:
    - host: test-ui-dev.local
      path: /
      service:
        name: test-ui
        port: 80

    - host: test-api-dev.local
      path: /
      service:
        name: test-api
        port: 80

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 1Gi