env: dev
namespace: praksa-task-dev
appName: test
ingress:
  enabled: true
  class: nginx

api:
  name: praksa-task-api
  port: 8080
  host: api.dev.local

ui:
  name: praksa-task-ui
  port: 3030
  host: ui.dev.local
