apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.chart }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.rules }}
    - host: {{ .host }}
        http:
        paths:
            - path: {{ default "/" .path }}
            pathType: Prefix
            backend:
                service:
                name: {{ .service.name }}
                port:
                    number: {{ .service.port }}
    {{- end }}


