apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.api.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.api.name }}-service-{{ .Values.env }}
                port:
                  number: {{ .Values.api.servicePort }}

    - host: {{ .Values.ui.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ui.name }}-service-{{ .Values.env }}
                port:
                  number: {{ .Values.ui.servicePort }}
