apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .host }}
    http:
      paths:
      - path: {{ default "/" .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .service.name }}
            port:
              number: 80
