replicaCount: 5

env: uat

name: praksa-task-ui

image:
  repository: ghcr.io/gusmarko/praksa-task-ui/praksa-task-ui
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 3002 

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

namespace: praksa-task-uat
