name: Apply Terraform Changes

on:
    push:
        branches:
            - main
            - dev

jobs:
  buildAndDeploy:
    runs-on: runner-infra
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Kubernetes resources
        shell: powershell
        run: |
          Set-Location -Path "./terraform-iac" 
          echo Get-Location
          terraform init
          terraform plan -var-file="dev.tfvars"
        #   terraform apply -auto-approve