name: Deploy Terraform Changes

on:
    push:
        branches:
            - main
            - dev
            - qa
            - uat

jobs:
  buildAndDeploy:
    runs-on: runner-infra
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Init
        shell: powershell
        run: |
          $env:PATH = "C:\Program Files\Terraform;$env:PATH"
          Set-Location -Path "./terraform-iac"
          terraform init

      - name: Select or create workspace
        shell: powershell
        run: |
          $env:PATH = "C:\Program Files\Terraform;$env:PATH"
          Set-Location -Path "./terraform-iac"
          $ws = "${{ github.ref_name }}"
          terraform workspace select $ws
          if (-not $?) {
            terraform workspace new $ws
            terraform workspace select $ws
          }

      - name: Deploy tf resources
        shell: powershell
        run: |
          $env:PATH = "C:\Program Files\Terraform;$env:PATH"
          Set-Location -Path "./terraform-iac"
          $branchName = "${{ github.ref_name }}"
          terraform destroy -auto-approve -var-file="$branchName.tfvars" 