name: Plan Terraform Changes

on:
    pull_request:
        types: opened
        branches:
            - main
            - dev
            - qa
            - uat

jobs:
  buildAndDeploy:
    runs-on: runner-infra
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Select or create workspace
        run: |
          $ws = "${{ github.ref_name }}"
          terraform workspace select $ws
          if (-not $?) {
            terraform workspace new $ws
            terraform workspace select $ws
          }

      - name: Plan tf changes
        shell: powershell
        run: |
          Set-Location -Path "./terraform-iac"
          $branchName = "${{ github.ref_name }}"
          terraform init
          terraform plan -var-file="$branchName.tfvars" 