name: Apply Terraform Changes

on:
    pull_request:
        types: 
            - opened
        branches:
            - main
            - dev
            - qa
            - uat

jobs:
  planTerraformResources:
    runs-on: runner-infra
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Kubernetes resources
        shell: powershell
        run: |
          Set-Location -Path "./terraform-iac"
          $env:PATH = "C:\Program Files\terraform;$env:PATH"
          $branchName = "${{ github.ref_name }}"
          if (Test-Path -Path "C:\Users\marko.gusic\git\terraform-states\$branchName\terraform.tfstate" -PathType Leaf) {
            Copy-Item -Path "C:\Users\marko.gusic\git\terraform-states\$branchName\terraform.tfstate" -Destination "./" -Force
          }
          terraform init 
          terraform plan -var-file="$branchName.tfvars"
          Copy-Item -Path "./terraform.tfstate" -Destination "C:\Users\marko.gusic\git\terraform-states\$branchName\terraform.tfstate" -Force