name: Plan Terraform Changes

on:
    pull_request:
        types: opened
        branches:
            - main
            - dev
            - qa
            - uat

jobs:
  buildAndDeploy:
    runs-on: runner-infra
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Init
        shell: powershell
        run: |
          $env:PATH = "C:\Program Files\Terraform;$env:PATH"
          Set-Location -Path "./terraform-iac"
          terraform init

      - name: Select or create workspace
        shell: powershell
        run: |
          $env:PATH = "C:\Program Files\Terraform;$env:PATH"
          Set-Location -Path "./terraform-iac"
          $ws = "${{ github.base_ref }}"
          terraform workspace select $ws
          if (-not $?) {
            terraform workspace new $ws
            terraform workspace select $ws
          }

      - name: Plan tf changes
        shell: powershell
        run: |
          $env:PATH = "C:\Program Files\Terraform;$env:PATH"
          Set-Location -Path "./terraform-iac"
          $branchName = "${{ github.base_ref }}"
          terraform plan -var-file="$branchName.tfvars" 